# Generated by Django 4.2.7 on 2023-12-02 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_task_more_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='more_description',
        ),
    ]
