# Generated by Django 4.2.7 on 2023-12-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_task_more_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='more_description',
            field=models.TextField(default=1996, max_length=500, verbose_name='ДОП Описание'),
            preserve_default=False,
        ),
    ]
